# Generated by Django 4.1.1 on 2022-10-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.BigIntegerField(unique=True)),
                ('price_dollar', models.IntegerField()),
                ('price_ruble', models.FloatField()),
                ('delivery_time', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
