# Generated by Django 4.1.1 on 2022-10-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
